networks:
  kafka-network:
    driver: bridge

volumes:
  kafka1:
    driver: local
  kafka2:
    driver: local

services:
  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    restart: unless-stopped
    ports:
      - '9096:9096'  # EXTERNAL 리스너 포트 매핑
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_NUM_PARTITIONS=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS=6000
      - KAFKA_CFG_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9093,1@kafka2:9093
      - KAFKA_KRAFT_CLUSTER_ID=HsDBs9l6UUmQq7Y5E6bNlw
      # 리스너 설정
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9096,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://localhost:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#    volumes:
#      - 'kafka1:/bitnami/kafka'
    networks:
      - kafka-network

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    restart: unless-stopped
    ports:
      - '9097:9097'  # EXTERNAL 리스너 포트 매핑
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9093,1@kafka2:9093
      - KAFKA_CFG_NUM_PARTITIONS=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CFG_GROUP_MIN_SESSION_TIMEOUT_MS=6000
      - KAFKA_CFG_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS=2
      - KAFKA_KRAFT_CLUSTER_ID=HsDBs9l6UUmQq7Y5E6bNlw
      # 리스너 설정
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9097,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,EXTERNAL://localhost:9097
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#    volumes:
#      - 'kafka2:/bitnami/kafka'
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - '8000:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9092
    networks:
      - kafka-network

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=chat
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=chat
    volumes:
      - ./data/db:/var/lib/mysql:rw
    networks:
      - kafka-network

  app:
    container_name: app
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
      - kafka1
      - kafka2
    networks:
      - kafka-network